name: Perfect Interview Actions
run-name: ${{ github.actor }} is testing out Perfect Interview Actions 🚀
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Run linting
      #   run: npm run lint
      # - name: Build
      #   run: npm run build
      # - name: Run dev
      #   run: npm run dev
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Linting
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run dev
        run: yarn dev
